FROM php:7.4-fpm

RUN apt-get update \
    && apt-get install -y \
        bash \
        libpq-dev \
        libicu-dev \
        libzip-dev \
        zip \
        sudo \
    && docker-php-ext-configure zip --with-libzip \
    && docker-php-ext-install \
        pdo \
        pdo_pgsql \
        intl \
        zip \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* \
    && curl --insecure https://getcomposer.org/composer.phar -o /usr/bin/composer && chmod +x /usr/bin/composer \
    && composer self-update


ADD php.ini /usr/local/etc/php/conf.d/

workdir /var/www

COPY ./docker-entrypoint.sh /
RUN chmod +x /docker-entrypoint.sh
ENTRYPOINT ["/docker-entrypoint.sh"]
