version: '3.2'

services:
    nginx:
        image: nginx:latest
        ports:
            - "80:80"
        volumes:
            - .:/var/www/
            - ./docker/nginx:/etc/nginx/conf.d
            - ./var/log:/var/log/nginx/
        links:
            - php
    php:
        build: ./docker/php
        volumes:
            - .:/var/www
        ports:
            - 9000:9000
        links:
            - db
    db:
        image: mysql:5.7
        command: ["--default-authentication-plugin=mysql_native_password"]
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: ${DB_NAME}
            MYSQL_USER: ${DB_USER}
            MYSQL_PASSWORD: ${DB_PASSWORD}
